# 1. Partiamo da un'immagine Python ufficiale "leggera"
FROM python:3.12-slim

# 2. Impostiamo variabili d'ambiente per evitare file .pyc e buffer
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# 3. Creiamo la cartella di lavoro dentro il container
WORKDIR /app

# 4. Installiamo le dipendenze di sistema (es. per Postgres)
RUN apt-get update && apt-get install -y libpq-dev gcc && rm -rf /var/lib/apt/lists/*

# 5. Copiamo il file delle dipendenze e le installiamo
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 6. Copiamo tutto il resto del codice del backend
COPY . .

# 7. Il comando che avvia l'app (es. con Gunicorn o Uvicorn per i WebSockets)
CMD ["uvicorn", "app.config.asgi:application", "--host", "0.0.0.0", "--port", "8000"]